name: Staking
version: 1.3
description: A new, better, way of staking!
main: me.jet315.staking.Core
softdepend: [Vault,McMMO]
commands:
  Stake:
    description: The base command for the Staking plugin
    aliases: [staking,duel,pvp]